[2024-05-09T02:14:16.927+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-09T02:14:17.098+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag_v1.inaccurate manual__2024-05-09T02:07:43.320809+00:00 [queued]>
[2024-05-09T02:14:17.131+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag_v1.inaccurate manual__2024-05-09T02:07:43.320809+00:00 [queued]>
[2024-05-09T02:14:17.133+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-05-09T02:14:17.177+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): inaccurate> on 2024-05-09 02:07:43.320809+00:00
[2024-05-09T02:14:17.191+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3483) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-09T02:14:17.195+0000] {standard_task_runner.py:63} INFO - Started process 3485 to run task
[2024-05-09T02:14:17.205+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_dag_v1', 'inaccurate', 'manual__2024-05-09T02:07:43.320809+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpdd79lw_z']
[2024-05-09T02:14:17.211+0000] {standard_task_runner.py:91} INFO - Job 46: Subtask inaccurate
[2024-05-09T02:14:17.308+0000] {task_command.py:426} INFO - Running <TaskInstance: my_dag_v1.inaccurate manual__2024-05-09T02:07:43.320809+00:00 [running]> on host 2b3626ba2b72
[2024-05-09T02:14:17.505+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='satyendra' AIRFLOW_CTX_DAG_ID='my_dag_v1' AIRFLOW_CTX_TASK_ID='inaccurate' AIRFLOW_CTX_EXECUTION_DATE='2024-05-09T02:07:43.320809+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-09T02:07:43.320809+00:00'
[2024-05-09T02:14:17.522+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-09T02:14:17.523+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-09T02:14:17.525+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'inaccurate'"]
[2024-05-09T02:14:17.549+0000] {subprocess.py:86} INFO - Output:
[2024-05-09T02:14:17.564+0000] {subprocess.py:93} INFO - inaccurate
[2024-05-09T02:14:17.565+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-09T02:14:17.566+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-09T02:14:17.620+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=my_dag_v1, task_id=inaccurate, execution_date=20240509T020743, start_date=20240509T021417, end_date=20240509T021417
[2024-05-09T02:14:17.696+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-09T02:14:17.727+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-09T02:14:17.735+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
