[2024-05-09T01:31:43.662+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-09T01:31:43.702+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag_v1.choose_best_model scheduled__2024-05-08T00:00:00+00:00 [queued]>
[2024-05-09T01:31:43.715+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag_v1.choose_best_model scheduled__2024-05-08T00:00:00+00:00 [queued]>
[2024-05-09T01:31:43.716+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-05-09T01:31:43.742+0000] {taskinstance.py:2327} INFO - Executing <Task(BranchPythonOperator): choose_best_model> on 2024-05-08 00:00:00+00:00
[2024-05-09T01:31:43.752+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3052) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-09T01:31:43.755+0000] {standard_task_runner.py:63} INFO - Started process 3056 to run task
[2024-05-09T01:31:43.755+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_dag_v1', 'choose_best_model', 'scheduled__2024-05-08T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp96fmkl5d']
[2024-05-09T01:31:43.759+0000] {standard_task_runner.py:91} INFO - Job 17: Subtask choose_best_model
[2024-05-09T01:31:43.884+0000] {task_command.py:426} INFO - Running <TaskInstance: my_dag_v1.choose_best_model scheduled__2024-05-08T00:00:00+00:00 [running]> on host 2b3626ba2b72
[2024-05-09T01:31:44.087+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='satyendra' AIRFLOW_CTX_DAG_ID='my_dag_v1' AIRFLOW_CTX_TASK_ID='choose_best_model' AIRFLOW_CTX_EXECUTION_DATE='2024-05-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-08T00:00:00+00:00'
[2024-05-09T01:31:44.091+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-09T01:31:44.094+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-05-09T01:31:44.096+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-09T01:31:44.097+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 269, in execute
    return self.do_branch(context, super().execute(context))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/my_dag.py", line 17, in choose_best_model
    accuracies=ti.xcom_pull(taskids=[
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TaskInstance.xcom_pull() got an unexpected keyword argument 'taskids'
[2024-05-09T01:31:44.117+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=my_dag_v1, task_id=choose_best_model, execution_date=20240508T000000, start_date=20240509T013143, end_date=20240509T013144
[2024-05-09T01:31:44.139+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 17 for task choose_best_model (TaskInstance.xcom_pull() got an unexpected keyword argument 'taskids'; 3056)
[2024-05-09T01:31:44.176+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-09T01:31:44.206+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-09T01:31:44.212+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
